environment:
  nodejs_version: 15

platform:
  - x86
  - x64

init:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - cmd: cinst -y nsis
  - cmd: SET PATH=C:\Program Files\NSIS\;C:\Program Files (x86)\NSIS\;%PATH%

for:
-
  branches:
    only:
      - master
  environment:
    NODE_ENV: production
  install:
    - cmd: npm ci --only=production
  build_script:
    - cmd: npm run move-ui-production
    - cmd: npm run bundle
    - cmd: npm run package:only
    - cmd: set S3_BUCKET=strawbees-appveyor-builds
    - cmd: npm run publish
-
  branches:
    only:
      - develop
      - /feature*/
  environment:
    NODE_ENV: stage
  install:
    - cmd: npm ci --only=production
    - cmd: git clone https://github.com/strawbees/code-ui.git
    - cmd: cd code-ui
    - cmd: git checkout develop
    - cmd: npm ci
    - cmd: npm link
    - cmd: cd %APPVEYOR_BUILD_FOLDER%
    - cmd: npm link "@strawbees/code-ui"
  build_script:
    - cmd: set CONFIG=desktop_stage
    - cmd: npm run build-ui
    - cmd: npm run move-ui-develop
    - cmd: npm run bundle
    - cmd: npm run package:only
    - cmd: set S3_BUCKET=strawbees-downloads-stage
    - cmd: npm run publish

version: "{build}"

skip_tags: true
